spring:
  application:
    name: seplag-senior-api

  # Ligação ao Banco de Dados PostgreSQL do Docker
  datasource:
    url: jdbc:postgresql://localhost:5432/musicdb
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver

  # Configuração do Flyway (Organizador automático das tabelas)
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Limite de tamanho para as fotos das capas
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# Configurações do Storage MinIO
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: capas-albuns

# Segurança JWT (Exigência do Edital: 5 minutos de validade)
jwt:
  secret: 9a4f2c3d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z
  expiration: 300000